#!/bin/bash

# Function to check if Homebrew is installed
check_homebrew_installed() {
    if command -v brew >/dev/null 2>&1; then
        echo "Homebrew is already installed."
        return 0
    else
        echo "Homebrew is not installed."
        return 1
    fi
}

# Function to install Homebrew
install_homebrew() {
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

# Function to install Homebrew Bundle
install_brew_bundle() {
    echo "Installing Homebrew Bundle..."
    brew tap homebrew/bundle
}

# Function to run install.sh from /homebrew
run_homebrew_install() {
    local brewfile_dir="$(dirname "$0")/homebrew"
    local brewfile_path="$brewfile_dir/install.sh"

    chmod +x "$brewfile_path"
    cd "$brewfile_dir" && ./install.sh
    cd ..
}

# Function to run setup_alacritty_config.sh from /alacritty
run_alacritty_config() {
    local alacritty_config_dir="$(dirname "$0")/alacritty"
    local alacritty_config_path="$alacritty_config_dir/setup_alacritty_config.sh"

    chmod +x "$alacritty_config_path"
    cd "$alacritty_config_dir" && ./setup_alacritty_config.sh
    cd ..
}

# Main script
check_homebrew_installed
if [ $? -ne 0 ]; then
    install_homebrew
    if [ $? -eq 0 ]; then
        echo "Homebrew installed successfully."
        install_brew_bundle
        run_brew_bundle
    else
        echo "Failed to install Homebrew."
        exit 1
    fi
else
    echo "No installation needed."
    install_brew_bundle
    run_homebrew_install
    run_alacritty_config
fi
