#!/bin/bash

# Run homebrew.sh from /homebrew
setup_homebrew() {
    local brewfile_dir="$(dirname "$0")/homebrew"
    local brewfile_path="$brewfile_dir/homebrew.sh"

    chmod +x "$brewfile_path"
    cd "$brewfile_dir" && ./homebrew.sh
    cd ..
}

# Run zsh.sh from /zsh
setup_zsh() {
    local zsh_config_dir="$(dirname "$0")/zsh"
    local zsh_config_path="$zsh_config_dir/zsh.sh"

    chmod +x "$zsh_config_path"
    cd "$zsh_config_dir" && ./zsh.sh
    cd ..
}

# Run alacritty.sh from /alacritty
setup_alacritty() {
    local alacritty_config_dir="$(dirname "$0")/alacritty"
    local alacritty_config_path="$alacritty_config_dir/alacritty.sh"

    chmod +x "$alacritty_config_path"
    cd "$alacritty_config_dir" && ./alacritty.sh
    cd ..
}

# Run mas.sh from /mas to install apps from the AppStore
setup_mas() {
    local mas_config_dir="$(dirname "$0")/mas"
    local mas_config_path="$mas_config_dir/mas.sh"

    chmod +x "$mas_config_path"
    cd "$mas_config_dir" && ./mas.sh
    cd ..
}

# Main script
setup_homebrew
setup_zsh
setup_alacritty
setup_mas
